---
- name: Test Telnet Connectivity to Remote Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test Connection
      wait_for:
        host: 3.111.30.30
        port: 3390
        state: started
        timeout: 10
      register: tcp_connectivity_result

    - name: Display TCP Connectivity Result
      debug:
        var: tcp_connectivity_result
