---
- name: Ping test for linux clients
  hosts: all
  gather_facts: True
  become: yes
  become_method: runas
  become_user: administrator

  vars_files:
    - ./vars/ext_vars.yml
  
  tasks:
    - name: ping
      win_ping:

    #- name: Set os_patching directory path
      #set_fact:
        #os_patching_folder: ajinkyagadge/directory2
        #os_patching_folder_certificates : ajinkyagadge/directory21/certificates

    - name: Create os_patching directory
      file:
        path: "{{ os_patching_folder }}"
        state: directory
        recurse: yes

   # - name: Copy the template file
   #   template:
   #     src: ajinkyagadge/clear-softwaredistribution.ps1.j2  # Assuming you have a Jinja2 template file
   #     dest: "{{ os_patching_folder }}/clear-softwaredistribution.ps1"
   #   vars:
   #     os_patching: "{{ os_patching }}"  # Assuming os_patching is defined in your Ansible variables
   
    - name: Copy the clear-softwaredistribution.ps1 script
      copy:
        src: projectresideo/clear-softwaredistribution.ps1.j2                                    # Source directory containing the script template
        dest: "{{ os_patching_folder }}/clear-softwaredistribution.ps1"
        remote_src: yes
        mode: '0664'

    - name: Create certificates directory and chek it exists or not
      ansible.builtin.file:
        path: "{{ certificates_folder }}"
        state: directory
      when: certificates_folder is defined and certificates_folder is not none

    - name: Print File Paths
      ansible.builtin.debug:
        msg: "File Path: {{ item }}"
      loop: "{{ file_paths }}"

    - name: Copy Certificates
      copy:
        src: "{{ project_folder }}/{{ item }}"
        dest: "{{ certificates_folder }}/{{ item }}"
        remote_src: yes
      when: certificates_folder is defined and certificates_folder is not none
      loop: "{{ file_paths }}"
      
